### ISSUE TITLE
Out of date readme.md

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/configurate#104]
`Javadocs: http://configurate.aoeu.xyz/apidocs` needs to point to new JD location.

```
dependencies {
    compile 'ninja.leaping.configurate:configurate-hocon:3.3'
}
```

Needs new version, new group.

And same for maven.

```
<dependency>
    <groupId>ninja.leaping.configurate</groupId>
    <artifactId>configurate-hocon</artifactId>
    <version>3.3</version> <!-- Update this with the most recent version -->
</dependency>
```

http://configurate.aoeu.xyz/configurate-hocon/dependency-info.html hasn't been updated or moved for the 3.4 release.

And we could show dependency info / alternative config formats supported in the readme.

**Comment by lucko** [comment]
Resolved by #118
