### ISSUE TITLE
Explore japicmp-gradle-plugin as a Binary Compatibility checker?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Configurate#107]
https://github.com/melix/japicmp-gradle-plugin

**Comment by zml2008** [comment]
I've tested out japicmp by running it manually and while it is a useful tool for manual inspection, it has what I believe to be false positives that make automated checks difficult. The maven plugin is also quite limited -- what I'd like is something that could fetch older versions of the artifact from a maven repository automatically.

For anyone wondering what this looks like, I've run a report comparing 3.6.1 with 3.7 (as of 26fe47d473b33e5792250cb29138778f8dee489e) -- it's available at https://files.stellardrift.ca/mc/configurate-core-changes-3.6.1-3.7.html

I think the idea is still useful, but as long as it's possible to do manual reports i don't think it'll be super high priority.
