### ISSUE TITLE
TypeSerializerCollection registration manual ordering

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/configurate#108]
`collection.get(TypeToken<?>)` returns first matching, not best matching.
If i add `collection` serializer and then `set` serializer and try to serialize any set - collection serializer will be used.

UPD:
Order sensitivity is documented. With this behavior it's impossible to manage search order, if i add Collection serializer, i should re-implement Set and List serializer, because Collection serializer will take advantage.

**Comment by lucko** [comment]
The `Set` and `List` serializers just need to be registered before (or in a child serializer collection) the `Collection` one to take priority.

I don't see this as being an issue.

**Comment by XakepSDK** [comment]
It's impossible to do this without own re-implementation.

**Comment by lucko** [comment]
I don't understand the point you're trying to make

**Comment by lucko** [comment]
@XakepSDK Any update? :)

**Comment by XakepSDK** [comment]
Ah, forgot about this. I'll make example tomorrow. 100%

**Comment by lucko** [comment]
Ok great, thank you :)

**Comment by XakepSDK** [comment]
I can't reproduce now.
