### ISSUE TITLE
Deserializing maps with Objects that have a custom serializer

### ISSUE THREAD

**Issue by Valandur** [SpongePowered/configurate#110]
In `SpongeVanilla 59` I was able to use following code to load a map of objects:

```java
@ConfigSerializable
public class PermissionConfig {
    @Setting
    public Map<String, PermissionStruct> keys = new HashMap<>();
}
```

where `PermissionStruct` had a custom serializer that i registered at startup.

Deserializing in `SpongeVanilla 59` and lower works, but in `SpongeVanilla` 75 this throws an error telling me that PermissionStruct needs an empty constructor (to me it sounds like it's ignoring the custom serializer).

`PermissionStruct` doesn't have an empty constructor, but it never needed one, since the custom serializer uses a constructor with arguments.

Adding an empty constructor causes the generated `PermissionStruct` objects to be empty.

**Comment by Valandur** [comment]
I'm using a custom serializer for the `PermissionStruct` class, but not for the `PermissionConfig` class.

Is there a recent change that made it so that I can't mix those two anymore?

**Comment by XakepSDK** [comment]
If that worked, then should work.

**Comment by XakepSDK** [comment]
Can you try 1.12.2-7.1.0-BETA-71?

**Comment by XakepSDK** [comment]
Haha, this is because of this commit: https://github.com/SpongePowered/configurate/pull/88

**Comment by Valandur** [comment]
Thank you <3 Do you still want me to try with BETA-71?

**Comment by XakepSDK** [comment]
No, it's definitely because of that commit.

**Comment by lucko** [comment]
Can you show the `PermissionStruct` class?

I don't see how this is related to that commit, which other serializer would be matching it?

**Comment by Valandur** [comment]
[This is the `PermissionStruct` class](https://github.com/Valandur/Web-API/blob/master/src/main/java/valandur/webapi/security/PermissionStruct.java)
[And this is the serializer for it](https://github.com/Valandur/Web-API/blob/master/src/main/java/valandur/webapi/security/PermissionStructSerializer.java)

**Comment by lucko** [comment]
You need to remove the `@ConfigSerializable` annotation from that class if you want it to be handled by your custom serializer.

**Comment by XakepSDK** [comment]
`PermissionConfig` handled by annotation serializer and `PermissionStruct` handled by custom serializer.

**Comment by Valandur** [comment]
Works :+1: why has this behavior changed?

**Comment by lucko** [comment]
1) To make the implementation consistent with the documentation - https://github.com/SpongePowered/configurate/wiki/Object-Mapper#extending

2) To allow for #75
