### ISSUE TITLE
Allow providing comments for Map entries with ObjectMapper

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Configurate#112]
Currently, it's impossible to add comments to the individual configuration nodes that ObjectMapper creates for map entries. Any modifications made to the root node that `ObjectMapper` serializes to will be lost if the config is reloaded and saved.

One way to accomplish this might be to create a special value type, which wraps the comment and the actual value, A new default `TypeSerializer`would be added before the standard `MapSerializer`, with a `TypeToken` of `Map<?, SomeWrapperType`>. This would allow existing code to continue to serialize maps as normal, while allowing users to opt-in to the extra serialization functionality.

**Comment by zml2008** [comment]
Between attempting to preserve comments on map elements and exposing copies of the backing `ConfigurationNode`s through a type serializer, it should be possible to preserve comments in most cases starting with configurate 3.7
