### ISSUE TITLE
Exception when ConfigurationNode#getValue(TypeToken, DefaultObject) tries to store the default value.

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/configurate#113]
Since Sponge updated to the last version of configurate I'm experiencing an issue with `ConfigurationNode#getValue(TypeToken, DefaultObject)`. This method try to store and serialize the `DefaultObject` passed in argument if no object was stored before which is normal but to do this the method `ConfigurationNode#setValue(DefaultObject)` is called without the `TypeToken` passed in the first method and thus the second method throw an exception because configurate don't know how to serialize the unknow object. A simple fix would be to use `ConfigurationNode#setValue(TypeToken, DefaultObject)` in this case.

**Comment by kashike** [comment]
Could you please provide the stacktrace?

**Comment by Yeregorix** [comment]
https://pastebin.com/zuxSFaEJ
