### ISSUE TITLE
ConfigurationOptions is checked for equality when checking ConfigurationNode equality

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/configurate#114]
It seems to me that there isn't a particular reason for this. If someone is checking for ConfigurationNode equality they're almost always intending to check when the values are equal and (to a lesser importance) if the keys are equal.

In my opinion, `loader.load().equals(loader.load())` should be able to return `true`, and yet it doesn't. Given how ConfigurationOptions are created, `equals` may as well literally be a `==` check.

**Comment by lucko** [comment]
Yes, equality shouldn't account for options.

blood and I ran into this issue a few weeks ago, but I never got around to committing a fix. Feel free to PR :)

**Comment by FerusGrim** [comment]
Just wanted to make sure I wouldn't be wasting my time if I did. I'll hop right on it.
