### ISSUE TITLE
Annotation based serialization is broken

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/configurate#116]
SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3328.jar
UltimateChat and magibridge don't work with that SF version.
At least magibrdige uses annotation based serialization only.
https://github.com/Eufranio/MagiBridge/blob/api-7/src/main/java/com/magitechserver/magibridge/config/ConfigManager.java
exceptions https://gist.github.com/XakepSDK/5adf1a60257b84225c106694e4237213

**Comment by Shybella** [comment]
I'm using Magibridge on 3328 and working or is this problem coming from the both working together?

**Comment by XakepSDK** [comment]
Do you really run 3328? MagiBridge/UltimateChat(tested separately) doesn't work even without any mod or other plugin.

**Comment by Shybella** [comment]
![download](https://user-images.githubusercontent.com/4436776/43039331-a7abd80c-8d05-11e8-8d8b-d3838179d32c.png)

**Comment by XakepSDK** [comment]
What MagiBridge version?

**Comment by Shybella** [comment]
2.4.6 - latest

**Comment by XakepSDK** [comment]
Lolwut
https://gist.github.com/XakepSDK/6335e3c97657c9276c5b5046a591f00a
![Screenshot](https://puu.sh/B0Fy7/1f889801f6.png)

**Comment by dualspiral** [comment]
This has already been fixed in https://github.com/SpongePowered/configurate/issues/113, it's just awaiting release.
