### ISSUE TITLE
NumberSerializer is horribly broken, and can cause data loss

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/configurate#121]
Configurate's built-in [`NumberSerializer`](https://github.com/SpongePowered/configurate/blob/4bc49644ed4ffd5a458b9367cf7d16de8a485495/configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializers.java#L93) will properly serialize any class extending `Number`. However, when it deserializes a type, it will *silently ignore* all but a few hardcoded subclasses of `Number`. If the loaded config is later saved, data sill be silently deleted if any other subclasses of `Number` are used (e.g. `BigDecimal`).

Since Configurate doesn't even log a warning, developers will have no idea where their data loss is coming from.

**Comment by ryantheleach** [comment]
The JavaDocs of Number say that

> Direct Known Subclasses:
> AtomicInteger, AtomicLong, BigDecimal, BigInteger, Byte, Double, DoubleAccumulator, DoubleAdder, Float, Integer, Long, LongAccumulator, LongAdder, Short


Are these all the subclasses of Number that Configurate should support?
