### ISSUE TITLE
What is a proper way to serialize an object including field comments to the file

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/configurate#124]
Let's say i have a class defined as 

    @ConfigSerializable
    public class Asd {

    	@Setting(value = "nodename", comment = "Comment")
         <Field signature>

So far im using 

			ObjectMapper.BoundInstance configMapper = ObjectMapper.forObject(data);
			HoconConfigurationLoader hcl = HoconConfigurationLoader.builder()
					.setPath(file.toPath())
					.build();
			SimpleConfigurationNode scn = SimpleConfigurationNode.root();
			configMapper.serialize(scn);
			hcl.save(scn);

But with this code no comments included within the file-

**Comment by dualspiral** [comment]
Use a `SimpleCommentedConfigurationNode` instead of the `SimpleConfigurationNode`, or `has.createEmptyNode()`.
