### ISSUE TITLE
[Feature] Add setKey method

### ISSUE THREAD

**Issue by NateCraft** [SpongePowered/Configurate#128]
Currently there is no method to change a key. You can set its value and you can delete it entirely but there there isn't a method to change the key itself besides copying its children and creating a new node with those values.

An addition to simply change the key itself would be quite helpful.

**Comment by system-operator** [comment]
Super cancer TBH. I ran into this last night and had always used old Spigot JSON examples etc. 

I was surprised and dumbfounded I can't add or change a single value on the fly. Seems like a serious oversight.

**Comment by zml2008** [comment]
The idea of a node is it is defined by its key. The correct way to 'change a key' is by setting the value of the node at the new path to the node at the old path.
