### ISSUE TITLE
Configuration does not accept objects of type class java.lang.Short

### ISSUE THREAD

**Issue by Elrol** [SpongePowered/Configurate#131]
I am trying to add an itemstack to the config, and it works just fine, until I try adding an item that is enchanted. I am using this:
`node.setValue(TypeToken.of(ItemStack.class), stack);`

And it throws an error (the title of the issue). Asked in the discord and they pointed me here. 

:)

**Comment by XakepSDK** [comment]
And show us stacktrace

**Comment by Elrol** [comment]
https://pastebin.com/9Tp6Ev9J

Put it there to keep it easier to read.

**Comment by Elrol** [comment]
Just curious about the status of this, I have tried making a temp workaround but it doesnt seem to have worked.

**Comment by MrZoraman** [comment]
I actually don't know if my pull request addresses your specific problem. I was able to recreate the error message and update the code to fix that problem, but I'll need to know what config backend (json, gson, yaml, etc) you're using to know for sure if the problem is fixed for you.

**Comment by Elrol** [comment]
I am using Gson at the moment, but thanks for working on it ^-^

**Comment by MrZoraman** [comment]
gson is one of the backends I worked on, so that should "fix" your problem. That is, you should be able to give it a short and it'll accept it. No promises that won't cause problems when de-serializing from json to a an ItemStack class.

**Comment by Elrol** [comment]
How would I go about getting the update so that I can put it on my test server and dev env

**Comment by p0kefreak** [comment]
Has there been any progress on this?

**Comment by Elrol** [comment]
Ok, so the latest version, 3.6, Is still throwing the error about not being able to use shorts

**Comment by Elrol** [comment]
I am not sure whats going on, The log is telling me that it cant do it, but its also using the old package name, so I am not sure at this point.

`java.lang.IllegalArgumentException: Configuration does not accept objects of type class java.lang.Short
	at ninja.leaping.configurate.ScalarConfigValue.setValue(ScalarConfigValue.java:51) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3392.jar:1.12.2-2705-7.1.0-BETA-3392]
	at ninja.leaping.configurate.SimpleConfigurationNode.insertNewValue(SimpleConfigurationNode.java:318) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3392.jar:1.12.2-2705-7.1.0-BETA-3392]
	at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:283) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3392.jar:1.12.2-2705-7.1.0-BETA-3392]
`

This was tested using v3.6

**Comment by zml2008** [comment]
This is an issue within Sponge's Configurate DataTranslator -- it writes the data view to the node as an untyped map, without verifying that whatever types within the map are actually supported by the underlying node.
