### ISSUE TITLE
Make TypeSerializerCollections immutable.

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Configurate#138]
Obviously this is breaking, one for 4.0.

#132 kind of points towards this, but allowing the TSCs to be mutable can cause all sorts of confusion. Configurate should have a base, immutable collection which should be overridable with derirative collections (which are also immutable).

Perhaps something like (super super draft):

```java
interface TypeSerializerCollection {

    <T> TypeSerializer<T> get(TypeToken<T> type);

    interface Builder {

        Builder with(TypeSerializerCollection collection);

        Builder register(TypeToken<T> type, TypeSerializer<? super T> serializer);

        Builder register(Predicate<TypeToken<T>> type, TypeSerializer<? super T> serializer);

        TypeSerilaizerCollection build();
    }
}
```

Overriding a serialiser would then be done as it is now, registering a child serialiser and using it yourself. This enforces the separation of user provided serialisers, which isn't happening in 3.x (because many just register their TSs to the global collection - you could end up with a new plugin coming in, registering the same type earlier and thus breaking the config of the original plugin).

This should also remove most of the concerns around overriding other serialisers, because you are _forced_ to create your own collection, which will override any parent collection. It does have the downside that, at least in Sponge, the default TSC would no longer contain Sponge serialisers, but I don't think that's a huge issue if we document it and make it easy to get at it (using an injection and/or a method on the `Sponge` object (or somewhere in the tree).

We may also want to add a `usingSerializers(TypeSerializerCollection)` helper method where we would normally update the `ConfigurationOptions` object to make it easier to use a different TSC when required (because it is potentially another pain point). Alternatively, we could add `getValue(TypeToken<T> type, T def, TypeSerializerCollection tsc)` and `setValue(`getValue(TypeToken<T> type, T def, TypeSerializerCollection tsc)` on nodes to make it easier (and clearer) on how you _could_ use a separate TSC.

**Comment by kashike** [comment]
https://github.com/SpongePowered/Configurate/compare/4.x...ticket/138
