### ISSUE TITLE
Keep comments on YAML files

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/Configurate#146]
I use YAML because it keeps the nodes in the same order when saving.
Unfortunately, this means that the config files lose their comments when they get re-saved by the plugin.

If this is not possible, would it be possible to make HOCON keep ordering? Or recommend a different loader?

**Comment by zml2008** [comment]
So looking into SnakeYaml a bit more, comments are discarded at the lexer level, so that would require a forked library to be able to read comments.

And for the hocon issue, take a look at #31
