### ISSUE TITLE
Move away from Guava?

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/Configurate#150]
Since Guava is one of the Minecraft libraries, by using it we have to maintain compatibility with every version shipped with versions of Minecraft we want to be able to work with.

This would also want to happen for 4.0 in order to consolidate breaking changes.

In order to avoid that, there are a few things that we use fairly heavily that are Guava:

- [ ] TypeTokens - https://github.com/leangen/geantyref looks like a possible replacement
- [x] Immutable collections - JDK 9 has these, but we can't use that yet :(
- [x] A few misc string manipulation things

[Here's the full list](https://gist.github.com/zml2008/cab45118e9a24de7099ef190ae86e386)

**Comment by simon816** [comment]
Would shading be a better option? I wouldn't replace Guava just because of Minecraft compatibility unless shading is not possible.

**Comment by zml2008** [comment]
Guava is a fairly large API to shade, and because guava classes are exposed in our API we wouldn't be able to relocate or minimize without causing issues, even if we did shade so we would run the risk of conflicting with anything else using guava (like MC)

**Comment by zml2008** [comment]
other option for type tokens (maybe?): https://github.com/PatchworkMC/typetools

**Comment by astei** [comment]
There are some usages of the Guava `Cache` (along with related implementations). We can probably replace this with [Caffeine](https://github.com/ben-manes/caffeine) as an almost drop-in standalone replacement. Crucially, Caffeine has no other dependencies other than the regular JDK.

The alternative would be to use a synchronized `LinkedHashMap` with manual weak keys and a size cap.

In one case (caching `TypeToken`s to `ObjectMapper`s) we may want to explore the option of foregoing any caching, on the premise that deserializing configurations is typically an one-time expense, however the performance impact of doing this would need to be evaluated.

**Comment by zml2008** [comment]
Our usage of Guava cache is fairly light -- the main reason we have the guava cache is to support the AnnotatedObject TypeSerializer -- so that ObjectMapper instances are cached for records within records. If you have field with a List of a mapped type, the object mapper is looked up individually for each element of the list. Admittedly that could be worked around by using something like gson's TypeAdapterFactory, but that will have to be evaluated in the ObjectMapper refactoring going on.
