### ISSUE TITLE
Bump lightbend/config to include patch allowing long strings of numbers as map keys

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Configurate#153]
The current version included of https://github.com/lightbend/config includes a bug that prevents using long strings of numbers as map keys, as it tries converting them to an integer for comparison purposes. This doesn't work due to the length, which is checked in newer versions.

**Comment by zml2008** [comment]
Hi! In Configurate 3.7 snapshots the `lightbend/config` dep has been bumped up to 1.4.0, which should fix this issue. That release is pretty much complete, so I'll try to get a final version pushed in the next few days.
