### ISSUE TITLE
Getting started wiki contains invalid hocon version for gradle

### ISSUE THREAD

**Issue by arphox** [SpongePowered/Configurate#154]
Hi!

I was trying to follow the [getting started guide](https://github.com/SpongePowered/Configurate/wiki/Getting-Started), but gradle could not download the required version.

The guide says:
```
dependencies {
    implementation("org.spongepowered:configurate-hocon:3.7")
}
```

But the working one for me is only:
```
    implementation "org.spongepowered:configurate-hocon:3.7-SNAPSHOT"
```

Is this problem for only me, or is the guide incorrect?

**Comment by zml2008** [comment]
the guide is correct, configurate 3.7 just hasn't been published to the sponge maven repo yet. Add `https://repo.glaremasters.me/repository/permissionsex` to your build file for now.
