### ISSUE TITLE
Support initialising otherwise null fields on ConfigSerializable annotated classes

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Configurate#156]
[As briefly discussed in Discord](https://discordapp.com/channels/142425412096491520/539537645152239626/730788329213132850), we had a field that we didn't provide a default for (so was `null`). In the Sponge global config, it makes no sense for any entry to be `null`. 

It would be nice to allow Configurate initialise objects in the `ConfigSerializable` classes if population from a node would otherwise set `null` on a field. This should probably be optional via an option on the `ObjectMapper` builder.

**Comment by XakepSDK** [comment]
> it makes no sense for any entry to be null.
What about primitive wrappers?
