### ISSUE TITLE
Configurate doesn't work correctly when folders are not made

### ISSUE THREAD

**Issue by tyhdefu** [SpongePowered/Configurate#161]
Despite what the sponge docs says, that configurate deals with non-existant folders: [When your plugin is running for the first time, returned pathnames for configuration files and directories may not yet exist. If you delegate all reading / writing of files to Configurate, you do not need to worry about non-existent paths as the library will handle them appropriately.](https://docs.spongepowered.org/stable/en-GB/plugin/configuration/index.html)

I have found in more than one plugin, that configuration files are not created and, errors about FileNotFoundExceptions for the temp files that should have been created occur on saving when the folders do not exist. A simple Path.toFile().mkdirs() fixes these errors. (Also, the folders are not made, either, so this issue persists every restart until the folders are made).

It would be nice if Configurate either dealt with these, or updated the sponge docs to either tell the plugin devs to call mkdirs() or atleast not say that it does something it doesn't.
If you need any more details feel free to comment :)

**Comment by zml2008** [comment]
I believe this was fixed in Configurate 3.7 (except for file watchers). Let me know if you can still reproduce it.
