### ISSUE TITLE
HOCON ordering vs comments

### ISSUE THREAD

**Issue by kotx** [SpongePowered/Configurate#162]
Currently users of this library are forced to choose between having comments using the HOCON loader and having ordering using other loaders. Is there *any* way to have both proper ordering and comments on nodes? This is very irritating for me.

**Comment by zml2008** [comment]
it's a limitation of the HOCON library. not going to change until i get a chance to replace hocon entirely.

**Comment by kotx** [comment]
Is it possible to have comments on other loaders, then?

**Comment by XakepSDK** [comment]
YAML and XML supports comments.
GSON supports reading json with comments, but not writing

**Comment by zml2008** [comment]
xakep, please don't comment if you're just going to be wrong. 

XML is the only other format that can roundtrip comments. yaml and json will accept input with comments but will not store comments and will not write comments.

PRs will be accepted to change this behaviour.
