### ISSUE TITLE
Save error in Windows (AccessDeniedException)

### ISSUE THREAD

**Issue by AlessioDP** [SpongePowered/Configurate#164]
Since 1.7 I problems with `configurate-yaml` and `loader.save(...)` method.

Whenever I execute:
```java
// ConfigurationLoader dataLoader;
// ConfigurationNoed dataNode;
dataLoader.save(dataNode);
```

There is a warning in console:
```
Error in PartiesFileDispatcher at removeParty_147: AccessDeniedException > E:\Servers\mcss\servers\Bungee_1.16.1\plugins\Parties\28722883721391database.yml.tmp -> E:\Servers\mcss\servers\Bungee_1.16.1\plugins\Parties\database.yml 
sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
java.nio.file.Files.move(Files.java:1395)
com.alessiodp.parties.libs.configurate.loader.AtomicFiles$AtomicFileWriter.close(AtomicFiles.java:98)
java.io.BufferedWriter.close(BufferedWriter.java:266)
com.alessiodp.parties.libs.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:171)
com.alessiodp.parties.core.common.storage.file.YAMLDao.saveFile(YAMLDao.java:55)
com.alessiodp.parties.common.storage.dispatchers.PartiesFileDispatcher.removeParty(PartiesFileDispatcher.java:145)
com.alessiodp.parties.common.storage.PartiesDatabaseManager.lambda$removeParty$5(PartiesDatabaseManager.java:109)
java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

The result is a correct database (the data is saved correctly) but there is the warning and a file `28722883721391database.yml.tmp` is created and not eliminated.

Some info about how it is handled:
- Plain server with just LuckPerms and my plugin
- The removeParty (the method executed) is executed in an async **single** thread (not server main thread)
- The tested server is BungeeCord (Build #1536 - latest one currently)
- Both `configurate` and `configurate-yaml` are in the plugin jar

**Comment by zml2008** [comment]
This sounds like some sort of filesystem permissions issue -- I develop on windows and haven't been able to reproduce this. Do you happen to have a runnable example that can reproduce it?

**Comment by AlessioDP** [comment]
I completely deleted the plugin folder then let it regenerate it and now it works :P

I tested it in 2 different servers but I copy pasted the plugin folder so the permission issue was still there, really strange issue.

Sorry for the issue ;)

**Comment by zml2008** [comment]
No worries, glad to hear it was resolved :)
