### ISSUE TITLE
IndexOutOfBoundsException when doing node.getValue(token, defaultInstance)

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Configurate#184]
Recently (as of newer Sponge versions) my plugins started erroring on config initialization. I reproduced this on the latest version of SpongeVanilla.

Error: https://gist.github.com/Eufranio/619a4d50688a615c69658db2e74b0229
Config code: https://github.com/Eufranio/StorageUtils/blob/master/src/main/java/io/github/eufranio/config/Config.java#L40

**Comment by zml2008** [comment]
Thanks for reporting! This issue should be fixable for 4.1.

In the meantime on 3.7, you will have to work around the underlying issue, which is that in any node that isn't already a map (including uninitialized ones), an entry with an integer key is assumed to be an element of a list.

You can most likely work around this by initializing the appropriate nodes to an empty map before saving, using a non-integer type for the map keys (Long, Short, etc, or even String), or shipping a patched MapSerializer with your plugin and using a customized type serializer collection (applied in `ConfigurationOptions`).
