### ISSUE TITLE
ObjectMapper issues when distributing Configurate 'Jar-in-Jar'

### ISSUE THREAD

**Issue by jpenilla** [SpongePowered/Configurate#200]
This issue occurs when using the ObjectMapper and jij'ing Configurate 4.1.0. When jij'ing 4.0.0, the issue is not present.

When using shadow to shade and relocate 4.1.0, the issue is also not present.

https://paste.gg/p/anonymous/15a7ffffebdc491eab0812614dd66d8d

This can be reproduced by building the latest commit of https://github.com/jpenilla/TabTPS and attempting to load the fabric version, which jij's Configurate 4.1.0.

**Comment by zml2008** [comment]
Resolved with f97a6ab5c5dd43e8de06a10d3d5607f745511fbd for now, with longer-term plans discussed in #201 and #202.

Seems to be a restriction on setting final fields when using `VarHandles` -- I wonder if the restriction could be relaxed by passing a custom MethodHandles.Lookup to the field discoverer as well. Probably best to not depend on writing `final` fields though.
