### ISSUE TITLE
[Maven] Compile errors with 4.1.0 and 4.1.1: Unsupported class file major version 60

### ISSUE THREAD

**Issue by Andre601** [SpongePowered/Configurate#204]
Since updating to 4.1.0 and later on to 4.1.1 do I get the following error when running `mvn clean install` on my project:
```
Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default) on project velocity: Error creating shaded jar: Problem shading JAR C:\Users\Andreas\.m2\repository\org\spongepowered\configurate-core\4.1.1\configurate-core-4.1.1.jar entry META-INF/versions/16/org/spongepowered/configurate/objectmapping/RecordFieldDiscoverer$1.class: java.lang.IllegalArgumentException: Unsupported class file major version 60
```

My project is a Maven project and build of 3 different modules: Core, BungeeCord and Velocity.
This error seems to happen in the Velocity module but not in Core or BungeeCord. But considering the build order being Core, Velocity, BungeeCord do I believe that BungeeCord would have the same issue when Velocity wouldn't.

The error seems to indicate an incompatible Java version (Java 16?) that I don't use? The source and target version are set to 1.8 and I myself use Java 11 (AdobtJDK) which is also configured as such in the Project settings of IntelliJ. The Language level is also set to 11.

My personal guess here is, that with the introduction of Multi-release jar functionality, as mentioned in Version 4.1.0's release notes, did you unintentionally force a specific Java version to be used that not everyone can or want to use right now.

I btw talk about this note made here:
![info](https://cdn.discordapp.com/attachments/584040473186926623/841252825899335690/unknown.png)

Here is the current pom.xml of the Velocity module:
https://paste.helpch.at/dabicopezo.xml

I appreciate any help in solving this.

**Comment by Andre601** [comment]
Issue is solved.

Adding a `<exclude>META-INF/versions/16/</exclude>` rule removed the error and made the project compile properly.

**Comment by zml2008** [comment]
The underlying issue is the `maven-shade-plugin` uses ASM to analyze class files it shades, and it hasn't had its ASM version bumped to be compatible with J16 class files. This change has been done in their latest git tree, but they haven't pushed out a release yet. Once the next `maven-shade-plugin` release is out, you should be able to compile properly.
