### ISSUE TITLE
Register serializer based on AnnotatedType

### ISSUE THREAD

**Issue by Machine-Maker** [SpongePowered/Configurate#286]
I'd love to have a serializer be valid if either the type or the field had an annotation present. I don't think it's possible to do that right now since TypeSerializerCollection just uses a type predicate.

**Comment by zml2008** [comment]
This is a reasonable addition -- I'm not sure how trivial it would be to do annotation-based matching in a declarative manner, but it could be done imperatively with a different type of predicate, and of course an AnnotatedType could be passed to the serializer for inspection.
