### ISSUE TITLE
Modifying child node with an integer key of a virtual parent node results in index exception

### ISSUE THREAD

**Issue by Konicai** [SpongePowered/Configurate#300]
Reproduction:
- Get a virtual node
- Get a child node under it with an integer key
- Set the value of the child node (or any under it)
- IndexOutOfBoundsException occurs 

The child node appears to be a ListConfigValue in this case.
If the parent node is set to *anything* before hand (other than null), the exception is avoided.

example and exceptions here: https://gist.github.com/Konicai/15376129dce8393c2be7ce41d44326a4

**Comment by Konicai** [comment]
It's also avoided if a non-integer key is added below the parent node, before adding any integer keys

**Comment by zml2008** [comment]
Ah yes, this is an issue I wrestled with a little while ago in 2f9630a62e1a8ef7d073b273d6ed9f30c9c19734. I think the definition for a likely list entry is too loose -- the logic around there should be worked on.
