### ISSUE TITLE
Following the README building steps results in an error

### ISSUE THREAD

**Issue by BlazingTwist** [SpongePowered/Configurate#302]
Your README states: 

> The following steps will ensure your project is cloned properly. [...] `git clone https://github.com/SpongePowered/Configurate.git`

However after doing that,  `gradle build` will result in this "helpful" error:
```
Execution failed for task ':vendor:applyPatches'.
> Process returned error code. Expression: (result == 0). Values: result = 128
```
because the projects submodules were not cloned.

Instead, you might want to provide this command `git clone --recurse-submodules https://github.com/SpongePowered/Configurate.git`

**Comment by zml2008** [comment]
Yeah, this ix less than ideal - I think the best solution would be in gitpatcher itself, either to auto-checkout submodules, or to provide a friendly warning - I just haven't had a chance to implement anything yet unfortunately

**Comment by zml2008** [comment]
Tracked in https://github.com/MinecraftForge/gitpatcher/issues/6
