### ISSUE TITLE
ConfigurationNode - Typo issue

### ISSUE THREAD

**Issue by Djaytan** [SpongePowered/Configurate#365]
Hello,

Typo issues are located here and around:
* https://github.com/SpongePowered/Configurate/blob/5695117e1a92dd1c3694053f453e6445d0d7c323/core/src/main/java/org/spongepowered/configurate/ConfigurationNode.java#L437

`require()d` -> `required()` (3 occurences of the issue in the file)

Best Regards,
Djaytan

**Comment by zml2008** [comment]
That's not a typo - it's the past tense of the call to the require() method.
