### ISSUE TITLE
@Setting annotation with no value or comment.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Configurate#40]
What is the expected behaviour when an @Setting annotation has no value or comment?

I can't see a test case for this, and in addition https://github.com/SpongePowered/SpongeCommon/issues/115

https://github.com/SpongePowered/SpongeCommon/blob/ed5b96c03ad68bea48ecc604269fff549a63e1bf/src/main/java/org/spongepowered/common/configuration/SpongeConfig.java#L204

Sql settings arn't being generated, but the commands module is. The only difference between the two I can see is that the commands module has a comment.

**Comment by zml2008** [comment]
The expected behavior is that the field name is used as the key, rather than whatever is in the value field of the configuration. I'm not sure why the SQL section isn't being created though -- I'll leave this open until that's resolved.
