### ISSUE TITLE
[Feature] XML Configuration Parsing

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/configurate#57]
Just an idea. I'm working on a project that's dealing with XML (We're being forced, I swear!), and I already use Configurate for pretty much everything, nowadays. Would it be possible to add XML parsing?

**Comment by pie-flavor** [comment]
I would definitely agree with this. This also probably warrants the use of a new interface, PropertiedConfigurationNode (to go with XML's attributes).

**Comment by FerusGrim** [comment]
@pie-flavor This would probably end up being required. Thankfully, it wouldn't necessarily need to live in `configurate-core`. Though, I'm not sure how @zml2008 handles issues like this.

**Comment by Zidane** [comment]
Closing in favor of the PR.
