### ISSUE TITLE
Lists in config get set to null

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/configurate#70]
This is my code: http://pastebin.com/9XZzPnV4

On first load, `limit-to-worlds=[]`. However, when I restart, it gets set to `limit-to-worlds=null` if the list is left empty. If there are entries in the list, it loads fine.

The same happens with:

```
        config = loader.load();

        CommentedConfigurationNode listNode = config.getNode("list-node");

        if (listNode.isVirtual()) {
            listNode.setValue(new ArrayList<String>()).setComment("test b node");
        }

        loader.save(config);
```

**Comment by Meronat** [comment]
Closed by 26062f20ac2c93791821c23e41528da569b126e8
