### ISSUE TITLE
[1.10.2] Sponge API 5, Configurate not detecting end of input in a config file.

### ISSUE THREAD

**Issue by DMCK96** [SpongePowered/configurate#87]
So in the rewards.conf file of TeslaCrate (Simon_Flash was unable to replicate but believes it's unrelated to teslacrate and more related to configurate and Spongeforge) it's loading my first node in this case lb-common, but then it's moving onto lb-uncommon as if it's part of the lb-common and causing the error. 

Absolutely no idea why this is occurring. 

**Versions:**
- SpongeForge: 1.10.2-2477-5.2.0-BETA-2731
- TeslaCrate: S5.2-t1.0.1-v2.0.1-legacy
- TeslaPowered: S5.2-v1.0.1

GIST Below:
[https://gist.github.com/DMCK96/bbadf6e7dbb8f0f1f1f34cfcc583cbfc](https://gist.github.com/DMCK96/bbadf6e7dbb8f0f1f1f34cfcc583cbfc)

Full server log attached also just incase.
[fml-server-latest.log](https://github.com/zml2008/configurate/files/1565189/fml-server-latest.log)

**Comment by ryantheleach** [comment]
The root nodes of HOCON seem to be unordered accoding to www.hoconlint.com

https://gist.github.com/ryantheleach/c895908d2350ddc6577317283889a83d/revisions

**Comment by ryantheleach** [comment]
I misread this issue originally, sorry.

**Comment by DMCK96** [comment]
The odd thing is @ryantheleach this actually resolved the issue, but we're unable to understand why it resolved the issue.
