### ISSUE TITLE
HoconConfigurationLoader cannot handle empty list normally

### ISSUE THREAD

**Issue by ustc-zzzz** [SpongePowered/Configurate#93]
A field including an empty list will be dropped silently (For example,  `{a: 42, b: []} => {a: 42}`) when it is parsed as HOCON file format, and the `node.getChildrenMap` method will only return a map of 1 key-value pair which should have been 2. However, `node.getList` method will return an empty list if the node is virtual, so this bug will only happen when iterating values instead of getting values.

The reason is that [`HoconConfigurationLoader`](https://github.com/SpongePowered/configurate/blob/master/configurate-hocon/src/main/java/ninja/leaping/configurate/hocon/HoconConfigurationLoader.java#L196) did not create a list before adding values. I don't know if similar bugs will also happen at YAML, Gson, etc. but I consider that those related codes should also be checked.

**Comment by ustc-zzzz** [comment]
How is it going now?

**Comment by Meronat** [comment]
I can look at this in a few days hopefully, but if you or maybe @lucko would like to contribute a PR, I'd be happy to review it and get it in as soon as possible.

**Comment by Eufranio** [comment]
News?

**Comment by lucko** [comment]
@Eufranio @ustc-zzzz @randombyte-developer

Can you provide me with a test case? I think I can see where the issue lies, but I'm not sure if it fixes the same problem.

**Comment by Lignium** [comment]
I seem to have stumbled upon the same problem.

`anEmptyListInHoconConfig.isVirtual() == false`

Will there be any resolution on this issue?
