### ISSUE TITLE
Add array serialization

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Configurate#95]
A user of my plugin reported this: https://pastebin.com/HEN9S5BU

The plugin serializes NBT data to a HOCON file. The data was created by a mod and apparently contains an `int` array. This is how it was fixed in Nucleus: https://github.com/NucleusPowered/Nucleus/issues/798

I was rather surprised that configurate doesn't support this.

**Comment by randombyte-developer** [comment]
Any comment on this?

**Comment by Karagra** [comment]
This is still an issue been a while since i first reported it
